export const REGISTER_ACTION = "REGISTER_ACTION";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_PRIVATE_KEY = "GET_PROFILE";
export const LOGIN_ACTION = "LOGIN_ACTION";
export const GET_POST = "GET_POST";
export const CLEAR_CURRENT_POST = "CLEAR_CURRENT_POST";
export const POST_LOADING = "POST_LOADING";
